import React, { useEffect } from 'react'
import "./PrivacyPolicy.css"

const PrivacyPolicy = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
      }, []);
  return (
    <div className='PrivacyPolicy'>
            <h4>PRIVACY POLICY FOR NoQu TECH SOLUTIONS PRIVATE LIMITED</h4>
            <p>At NoQu (including its subsidiaries or affiliated companies, hereinafter referred to as ‘NoQu’, ‘We’ or the ‘Company’), We understand that you are trusting us with confidential information and We believe that you have the right to know our practices regarding the information We may collect and use when you use our service or interact with us in any manner.</p>
            <p>This delineates the kinds of personal data We collect via the Platform, how We may utilize such data and the parties with whom We may share it. Additionally, We provide guidance on how you can contact us to update your preferences regarding communication or to address any inquiries you may have about our privacy protocols.</p>
            <p><b>NoQu</b> is a cloud-based SaaS platform that enables organizations to manage Time & Attendance and other related services. NoQu Mobile Apps are also included in this offering. In addition, NoQu operates the website www.noqu.in. A User may be either an entity, such as an Employer that has executed an agreement with NoQu or with NoQu’s resellers or distributors who provide NoQu’s services (“Customer”) or a Customer’s Users such as a Customer’s employees, who uses the Services or the website (“End Users”). (Customers and End Users shall collectively be referred to as “Users” or “you”).</p>
            <h5>SCOPE OF POLICY</h5>
            <p>This policy together with our Terms of Use applies to your use of:</p>
            <p>The <b>Account owner</b> is NoQu’s administrator for his/her company’s account created within NoQu. The Account Owner has full rights over the company account data and can create other company’s Users and grant them data access permissions. The Account Owner is responsible for all data entered, including employee images, demographic data, and any other data related to company employees and users.</p>
            <p>This Privacy Policy describes NoQu's policies and procedures on the collection, use, access, correction, and disclosure of your personal information on noqu.in (the “Site”), our Mobile Apps and Admin Web Dashboard. Your personal information includes any information which, either alone or with other data, is reasonably available to us or relates to you (“Personal Information”). This Privacy Policy also covers any of your Personal Information provided to us in connection with marketing of the services, features or content We offer (the “Services”) to our clients and/or the support We may give you with the provision of our Services and Mobile Apps.</p>
            <p>
            This Privacy Policy does not apply to any third-party applications or software accessible through the Site, the Services or the Mobile Apps, such as social media websites or partner websites (“Third-Party Services”). By using our Services, you acknowledge that you have read and understood this privacy policy. For purposes of the GDPR or European Economic Area data protection law (the “Data Protection Law”), the data controller of the data processed through the Service is the Customer who makes it available and permits End Users to access and use the Service or anyone on its behalf. For data retained through the website data processed outside the Service (i.e. contact details of potential customers or resumes submitted to us by potential employees for the purpose of engagement with NoQu), NoQu is the controller (the “Controller”).
            </p>
            <h5>Information we collect about you and how we use it</h5>
            <h5>Personal Information</h5>
            <p>We generally collect and process the following types of Personal Information: Personal Information which is being gathered through the Service consists of any personal details provided consciously and voluntarily by a Customer (Employer), End User or the Customer’s administrator or through your use of the NoQu Platform.</p>
            <p>This may include your name, gender, designation, phone number(s), department, employee ID, email address, company location, information the Customer chooses to collect and other information User may choose to provide to NoQu and to its employee.</p>
            <h5>Location Information:</h5>
            <p>If you are using the <b>NoQu Time and Attendance Management</b> (TAM) User App, We will utilize geo-fencing and capture your geolocation for time-keeping purposes. When using the NoQu TAM app, the Employer of the organization you are working for, may or may not enable GPS to capture geolocation. Geolocation services help Employers track your location for attendance management. The GDPR legal basis for processing this information is the contractual obligation to your Employer to perform the Services.</p>
            <p>For <b>NoQu Scan</b>, only geo-fencing is used and you (employees) cannot be actively tracked as your attendance is not marked through your personal devices.</p>
            <h5>Contact Information:</h5>
            <p>When you express an interest in obtaining additional information about the Services, the Site, or Mobile Apps, NoQu may ask you to provide your personal contact information, such as your name, email address, and phone number. This information is used to communicate with you by responding to your requests, comments and questions. The GDPR legal basis for processing this information is the legitimate interest in communicating with you and answering your questions.</p>
            <h5>Biometric & Attendance Information</h5>
            <p>We collect biometric data through our facial recognition feature to record check-ins/check-outs, if the Employer has requested logging in through face recognition. The face biometric is not used for any other purpose apart from enabling the attendance related services. The registered face data is retained as long as the User remains active and requires face recognition-based attendance services. This face data will be removed when the User is inactivated by the Account Owner. Additionally, the Account Owner can choose to remove the registered face of any active User if it is no longer needed as per organization processes. We do not share face data with any external third-parties except the sub-processor required for the operation of the App and to perform related services of user identification for time clocking. These sub-processors do not store user faces after the processing is completed.</p>
            <p>We collect time of check in/out and attendance data when you use the App. The GDPR legal basis for processing this information is the contractual obligation to your employer to perform the Services.</p>
            <h5>Device Information</h5>
            <p>When using the Mobile Apps, We may request access to your device’s camera and photo storage. This allows you to take and upload pictures and such access will only be used as per your choices. You can, at any time, revoke access at the device level. We do not access your device’s camera and photo storage without your permission. When you download and use the Mobile Apps, We automatically collect device information, such as the operating system version, type, hardware usage statistics, etc. The GDPR legal basis for processing this information is the contractual obligation to your Employer to perform the Services.</p>
            <h5>Non-personal Information</h5>
            <p>The first type of data is non-identifiable and anonymous information (“Non-personal Information”). We are not aware of the identity of the User from whom We have collected Non-Personal Information. Non-personal Information is any unconcealed information which is available to us while Users are using the Service or the website. Non-personal Information which is being gathered consists of technical and behavioral information, which may include the User’s Internet Protocol (IP) address used to connect your computer to the Internet, Uniform Resource Locators (URLs), operating system type, browser type, browser plug-in types and versions, screen resolution, Flash version, and time zone setting.</p>
            <h5>Data Collected as a Service Provider</h5>
            <p>As a service provider, NoQu systems only collect information as required by the Customer (Employer). Our Subscription Agreement governs the delivery, access, and use of the Services and Mobile Apps, including the processing of Personal Information and data submitted through Service accounts. The Customer (i.e. your Employer) controls their Platform and any associated client data. If you have any questions about specific Platform settings, the processing of Personal Information in the Platform, or its privacy practices, please contact the Customer Administrator of the Platform you use.</p>
            <p>As a data processor, We can provide a data processing agreement to Account Owners. If you are an Account Owner, you must comply with GDPR requirements. The Customer is responsible to collect any necessary consent, provide any notice where necessary to their respective End-Users and be compliant to applicable data protection laws. You can request a data processing agreement from us by emailing support@noqu.in.</p>
            <h5>Disclosure of Personal Data</h5>
            <h5>Third Party Services</h5>
            <p>At times, you may be able to access other Third-Party Services through the Site, such as by clicking on links to those Third-Party Services from within the Site. We are not responsible for the privacy policies and/or practices of these Third-Party Services, and you are responsible for reading and understanding those Third-Party Services’ privacy policies.</p>
            <h5>Information Shared with Our Service Providers</h5>
            <p>We do not share personal information about you with any third-party unless We have your permission or under the following circumstances:</p>
            <p>• To facilitate the operation of the App and Service and to perform related services such as and without limitations, maintenance services, database management, web analytics, and improvement the Service’s features or to assist us in analyzing how our Apps and Services are used. Third-parties may have access to personal information required to perform their functions but it may not use it for other purposes.</p>
            <p>• In certain situations, We may be required to disclose Personal Information in response to lawful requests by public authorities, including to meet national security or law enforcement. We also reserve the right to access, read, preserve, and disclose any information as We reasonably believe is necessary to (i) satisfy any applicable laws, regulations, legal processes, or governmental requests; (ii) enforce this Privacy Policy, including investigation of potential violations; (iii) detect, prevent, or otherwise address fraud, security, or technical issues; (iv) respond to user support requests; or (v) protect our rights, property, or safety. This includes exchanging information with other companies and organizations for fraud protection and spam/malware prevention. We require all third-parties to uphold the security of your Personal Information and handle it in accordance with applicable laws. We do not allow any Third-Party Service providers and sub-processors with whom We share your Personal Information to use it for their own purposes and are only permitted to process your Personal Information for specified purposes as instructed by us.Except as set forth above, you will be informed when your Personal Information is shared with third-parties and will be able to prevent such sharing. Without your consent, We will only share your Personal Information as described in this Privacy Policy..</p>
            <h5>Data Retention</h5>
            <p>Any Customer may request information regarding the storage and retention of data (“Audit”) by contacting us. NoQu shall make reasonable efforts to respond to the Audit in a reasonable time and subject to applicable law and to the protection of NoQu’s trade secrets (Customer’s personnel may be required to executed a non-disclosure agreements).</p>
            <p>NoQu will retain data it processes on behalf of its Customers only for as long as required to provide the Service to its Customers and as necessary to comply with its legal obligations, resolve disputes and enforce its agreements. The data in NoQu is backed up for system continuity purposes.</p>
            <p>Each User must keep the appropriate backup of its data. NoQu shall not be responsible for any deletion of data or for any breach to database or for any erroneous data unless otherwise agreed with its Customer.</p>
            <p>After a termination of services by a customer, we may begin the process to permanently delete the data after 30 days. Once begun, this process cannot be reversed and data will be permanently deleted. Some data will not be deleted and shall be kept in an anonymized manner.</p>
            <p>NoQu collects and retains metadata and statistical information concerning the use of the Service which are not subject to the deletion procedures in this policy and may be retained by NoQu for no more than required to conduct its business. Some data may be retained also on our third-party service providers’ servers in accordance with their retention policies. You will not be identifiable from this retained metadata or statistical information.</p>
            <p>Customer may retain Personal Information and other data about an End User, which the Controller owns and the End User may have no access to. If you have any questions about the Customer's right to retain and process your Personal Information you should raise this directly with the Customer. You hereby agree not to assert any claim against NoQu in this regard and waive any rights regarding such data and Personal Information including the right to view and control such data and information.</p>
            <p>Some metadata and statistical information concerning the use of the Service are not subject to the deletion procedures in this policy and may be retained by NoQu. We will not be able to identify you from this data</p>
            <p>Anonymized aggregated data may be retained by NoQu for as long as it is required to provide its Services. Contracts and billing information may be retained as required by NoQu.</p>
            <h5>Where do we store your Data?</h5>
            <p>The data We collect is hosted on AWS data centers located in India, which provide advanced security features and comply with the ISO 27001 standard. NoQu services are provided globally and We are headquartered in Tamil Nadu, India.</p>
            <h5>Data Security and storage of information</h5>
            <p>We have implemented measures designed to secure your personal data from accidental loss and from unauthorized access, use, alteration and disclosure. The safety and security of your information also depends on you. Where we have given you (or where you have chosen) a password for access to certain parts of the Services, you are responsible for keeping this password confidential. We ask you not to share your password with anyone. Steps taken to ensure data security:</p>
            <p>(a) All user information can only be accessed by authorized Users;</p>
            <p>(b) Users need to authenticate themselves with a username-password combination; and</p>
            <p>(c) All data is hosted on Amazon AWS.</p>
            <p>However, the transmission of information via public networks, such as the internet is not completely secure. Although We do our best to protect your personal data, We cannot guarantee the security of personal data transmitted through the Services. Any transmission of personal data is at your own risk. We are not responsible for the circumvention of any privacy settings or security measures contained on the Services</p>
            <p>Personal information is hosted on Amazon AWS in India, which provides advanced security features and is compliant with the ISO 27001 standard, among other certifications, as listed https://aws.amazon.com/compliance/iso-certified.</p>
            <p>NoQu limits access to personal data to those of its personnel who (i) require access to fulfill NoQu’s obligations under this Privacy Policy and agreements executed with NoQu; (ii) have been appropriately and periodically trained on the requirements applicable to the processing, care and handling of the Personal Information and (iii) are under confidentiality obligations as required under applicable law.</p>
            <p>NoQu shall act in accordance with its policies to promptly notify Customer in the event of any loss, theft, or unauthorized access to personal data processed by NoQu on behalf of Customer, subject to applicable law and instructions from relevant agencies or authorities. Furthermore, NoQu undertakes to cooperate with Customer in investigating and resolving any such security breach. In any security breach involving Personal Information, NoQu shall promptly take remedial measures, including without limitation, reasonable measures to restore the security of the Personal Information and limit unauthorized or illegal dissemination of the Personal Information or any part thereof.</p>
            <h5>Your Rights associated with your information</h5>
            <p>If We are storing your personal information, you have the following rights to your information based on the Services and your region:</p>
            <p>In the event that you have provided Personal Information to us via our website noqu.in, We will inform you whether We hold any of your Personal Information. You may access, correct, or request deletion of your Personal Information by contacting us at support@noqu.in. We will respond to your request within a reasonable timeframe.</p>
            <p>When acting as a service provider for our Customers, NoQu does not have a direct relationship with individuals whose Personal Information is provided to NoQu through the Services. An individual who is/was employed by one of our Customers and seeks to access, correct, amend, object to processing or profiling, or delete his/her Personal Information on the Platform, should direct his/her query to the HR or department concerned or the relevant personnel within the Customer organization that uses the Platform for which he/she works or used to work if he/she cannot make the appropriate changes via its access to the Platform provided by the Customer. Your Account Owner has taken consent from organization employees for all of your personal data shared with us. For the execution of any rights, including withdrawing consent, you have to approach your organization's Account Owner to facilitate the process.</p>
            <p>Our Customers and their End-Users can request access, correction, and modification of their personal data stored on the NoQu platform. End-Users can also contact us at support@noqu.in to access, correct, or delete their personal data. As a Processor, We will forward these requests to the relevant customers and assist them in responding, if required.</p>
            <p>The following rights are regarding your Personal Information that We collect directly from you and control. (This does not apply to data collected by our Customer organizations where We are the Processor of data.)</p>
            <h5>Right of Access</h5>
            <h5>What does it mean?</h5>
            <p>Individuals have the right to request access to their personal data.</p>
            <h5>How NoQu complies?</h5>
            <p>You can request details of your Personal Information We hold. We will confirm whether We are processing your Personal Information and disclose additional information, including the types of Personal Information, the sources it originated from, the purpose and legal basis for processing, the expected retention period, and safeguards regarding data transfers to non-EEA countries, subject to the limitations set out in applicable laws and regulations. We will provide you with a copy of your Personal Information free of charge.</p>
            <h5>Right of rectification</h5>
            <h5>What does it mean?</h5>
            <p>Individuals have the right to correct any missing, incorrect, or outdated information that has been stored about them.</p>
            <h5>How NoQu complies?</h5>
            <p>At your request, We will rectify incomplete or inaccurate parts of your Personal Information, subject to verification of the accuracy of the new information provided by you.</p>
            <h5>Right to be forgotten</h5>
            <h5>What does it mean?</h5>
            <p>Individuals have the right to request the deletion of their personal data or submit a "request to be forgotten" at any time if they no longer want their data to be stored or processed.</p>
            <h5>How NoQu complies?</h5>
            <p>At your request, we will delete your Personal Information if:</p>
            <p>• It is no longer necessary for us to retain your Personal Information;</p>
            <p>• You object to the processing of your Personal Information (see below) and there are no overriding legitimate grounds for such processing;</p>
            <p>• The Personal Information was processed illegally; or</p>
            <p>• The deletion of Personal Information is required for us to comply with our legal obligations.</p>
            <p>• We may decline your request for deletion if the processing of your Personal Information is necessary for (i) us to comply with our legal obligations; (ii) the establishment, exercise, or defense of legal claims or; (iii) the performance of a task carried out in the public interest.</p>
            <h5>Right to restrict processing</h5>
            <h5>What does it mean?</h5>
            <p>Individuals have the right to request a restriction on the processing of their personal data, pertaining to certain conditions or circumstances. When processing is restricted, data controllers are allowed to store the personal data but not use it. An individual can make a request for restriction verbally or in writing. Organizations will have one calendar month to respond to the request for restriction.</p>
            <h5>How NoQu complies?</h5>
            <p>At your request, we will restrict the processing of your Personal Information if:</p>
            <p>• You dispute the accuracy of your Personal Information;</p>
            <p>• Your Personal Information was processed illegally and you request limitation on processing rather than deletion of your Personal Information;</p>
            <p>• We no longer need to process your Personal Information, but you require it in connection with the establishment, exercise, or defense of legal claims; or</p>
            <p>• You object to the processing of your Personal Information pending verification as to whether an overriding legitimate ground for such processing exists.</p>
            <p>• We may continue to store your Personal Information to the extent required to ensure that your request to restrict processing is respected in the future.</p>
            <h5>Right to data portability</h5>
            <h5>What does it mean?</h5>
            <p>Individuals have the right to transfer their personal data from one electronic processing system to and into another electronic processing system at will, and if requested, companies have the new GDPR standard of 30 days to comply with the request. For example, switching from one social network to another or from one cloud provider to another.</p>
            <h5>How NoQu complies?</h5>
            <p>At your request, We will provide you with your Personal Information free of charge in a structured, commonly used, and machine-readable format if:</p>
            <p>• You provided us with your Personal Information;</p>
            <p>• The processing of your Personal Information is required for the performance of a contract;</p>
            <p>• Or The processing is carried out by automated means.</p>
            <h5>Right to object</h5>
            <h5>What does it mean?</h5>
            <p>Under GDPR, individuals have the "Right to Object” i.e. the data controllers can say that they no longer want the personal data processing to be carried out. In practice, the data subject can exercise the right to object more so with things related to direct marketing.</p>
            <h5>How NoQu complies?</h5>
            <p>Where We rely on our legitimate interests (or those of a third party) to process your Personal Information, you have the right to object to such processing on grounds relating to your particular situation, if you believe it impacts your fundamental rights and freedoms. We will comply with your request unless We have compelling legitimate grounds for the processing that override your rights and freedoms, or where the processing is in connection with the establishment, exercise, or defense of legal claims. We will always comply with your objection to processing your Personal Information for direct marketing purposes.</p>
            <h5>Rights in Relation to Automated Decision Making and Profiling</h5>
            <h5>What does it mean?</h5>
            <p>The GDPR has provisions on making a decision solely based on automated means without any human involvement, as well as the automated processing of personal data to evaluate certain aspects about an individual i.e. profiling. Profiling can be part of an automated decision-making process. GDPR applies to all forms of automated individual decision-making and profiling.</p>
            <h5>How NoQu complies?</h5>
            <p>You will not be subject to decisions with a legal or similarly significant effect (including profiling) that are based solely on the automated processing of your Personal Information, unless you have given us your explicit consent or when such processing is necessary for the performance of a contract with us.</p>
            <h5>Right to withdraw consent</h5>
            <p>You have the right to withdraw any consent you may have previously given us at any time. To exercise your rights in this section, We may ask you for certain identifying information to ensure the security of your Personal Information. To request to exercise any of the above rights, please contact us at support@noqu.in. We will respond to your request within 30 days or provide you with reasons for any delay.</p>
            <p>Usually, We will not charge you any fees in connection with the exercise of your rights. However, if your request is manifestly unfounded or excessive, such as due to its repetitive character, We may charge a reasonable fee, taking into account the administrative costs of handling your request. If We refuse your request, We will notify you of the relevant reasons.</p>
            <h5>Holding Information On Minors</h5>
            <p>Our Service is not directed to minors and We do not knowingly collect Personal Information from them. The Service can only be used by individuals who have reached the age of majority in the State and Province they reside.</p>
            <p>If We learn that We have collected Personal Information from a minor, We will take necessary steps to delete such information from our files as soon as possible.</p>
            <h5>Changes to our privacy policy</h5>
            <p>The terms of this Privacy Policy govern the use of the Service and any information collected in connection therewith, however, NoQu may amend or update this Privacy Policy from time to time. All changes to this Privacy Policy are effective as of the stated “Last Revised” date and your continued use of the Services will constitute your active acceptance of, and agreement to be bound by the changes to the Privacy Policy.</p>
            <p>If through mail to the primary email address specified in your account. You are responsible for ensuring We have an up-to-date, active, and deliverable email address for you, and for periodically visiting our website and reviewing this Policy to check for any changes.</p>
            <p>If you have any questions (or comments) concerning this Privacy Policy, send us an email or otherwise contact us at support@noqu.in and will make an effort to reply within a reasonable timeframe, no later than 30 business days.</p>

    </div>
  )
}

export default PrivacyPolicy
