import React, { useEffect } from 'react'
import "./PrivacyPolicy.css"

const TermsAndConditions = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
      }, []);
  return (
    <div className='PrivacyPolicy'>
        <h4>TERMS & CONDITIONS FOR NoQu TECH SOLUTIONS PRIVATE LIMITED</h4>
        <p>NoQu Tech Solution Private Limited (“Company” or “We” or “Us” or “Our”), having its office at Door No - 84, 2nd floor, Murugesan Naicker Complex, Greams Rd, Thousand Lights West, Thousand Lights, Chennai, Tamil Nadu 600006, India owns and operates a web/mobile application. “NoQu” available as iOS and android based applications (“App”) and the websites: (i) www.noqu.in; (“Website”). The App and Website shall hereinafter together be referred to as the “Site” or “NoQu”. You (hereinafter collectively referred to as “User(s)”/ “You”/ “Your”) may be accessing our Site from a computer or mobile phone device (through an iOS or Android application, for example) and these Terms of Use govern your use of our Site and your conduct, regardless of the means of access. By using the Site, you confirm that you accept these Terms of Use and that you agree to abide by them. Your use of the services and features of the Site shall be governed by these Terms and Conditions (hereinafter "Terms of Use") along with the Privacy Policy, as modified and amended from time to time. By mere accessing or using the Site, you are acknowledging, without limitation or qualification, to be bound by these Terms of Use and the Privacy Policies, whether you have read the same or not. ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR UNCONDITIONAL AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING. If you do not agree to any of the terms enumerated in the Terms of Use or the Policies, please do not use the Site. You are responsible to ensure that your access to this Site and material available on or through it are legal in each jurisdiction, in or through which you access or view the site or such material.</p>
        <h5>1. REGISTRATION OF USERS</h5>
        <p>You will need to sign-up with Us by filling the sign-up form by providing your registered mobile number and other requisite information about yourself or your organisation and open a NoQu account (“Account”). As a registered user, you further agree to update your Personal Information (as defined in the Privacy Policy) if needed and to be solely and entirely responsible for maintaining the confidentiality of your user account, login and password and any activity that may occur through your Account. You must ensure that the information provided by you is correct, complete and not misleading. You should also inform us promptly of any changes to the information that you have provided, by updating Your details, so we can communicate with You effectively. In the event, the information supplied by you is incorrect, incomplete and misleading, your registration may be cancelled and Your Account may be deactivated.</p>
        <h5>2. SUBSCRIPTION OF SERVICES</h5>
        <h5>a. Payment of Fees</h5>
        <p>NoQu provides paid services you will be required to make payment of subscription fees for the use of the advanced features available on the Site. The following payment options are available on the Site:</p>
        <p>i. Credit and debit cards</p>
        <p>ii. Cheque</p>
        <p>iii. Net banking/Direct Debit payments from banks in India. A list of available options will be made available at the time of the transaction.</p>
        <p>iv. Payment Wallets</p>
        <p>v. UPI</p>
        <p>To successfully subscribe to the paid services, the User is required to complete the transaction by making the payment for the services opted for.</p>
        <h5>b. Online transactions and Payment Rules</h5>
        <p>When you use Services as provided by the Site, you may opt to transfer payment to your staff/employee(s). To process such financial transactions, the Site may use third-party electronic payment processors or service providers (ESPs). You permanently authorise us to instruct such ESPs to handle Account deposits and withdrawals from your account. You also permanently agree that in accordance with your requests as submitted, we may give such instructions on your behalf. You agree to be bound by the terms and conditions of use of each ESP, as appropriate. In the event of a conflict between these Terms of Use and the ESP's terms and conditions, these Terms of Use shall prevail. Users should ensure that the instrument used to make the payment is his/her own. Users further understand and acknowledge the fact that NoQu is not a bank, a financial institution, or a non-banking financial corporation. We maintain a nodal bank account for the services offered on the Site. All payment instructions made by Users are submitted to the nodal bank in order to effect the payment to other Users.</p>
        <p>It is the sole responsibility of the Users to administer and manage the online banking and financial transactions and payments made through the Site. Users are solely responsible for acquainting themselves with, and complying with, all applicable laws of India, including those pertaining to online payments and transfer of funds through online and offline methods. Users have to be sure that they are complying with the requirements and regulations as framed by Reserve Bank of India (RBI) from time to time and any online monetary transaction in violation of the rules and regulations prescribed by the RBI and other applicable laws of India shall be solely attributable to the concerned User and We shall not be held liable in this regard.</p>
        <p>In case the payment instructions issued by you are not effected for any reason, you will be intimated by WhatsApp or SMS or push notifications to the mobile no specified by you in this regard. We assume no further responsibility in relation to failed transactions on the Site.</p>
        <h5>c. Third Party KYC Verification</h5>
        <p>The Site may require Users to upload certain information and documents that may be necessary to ascertain their eligibility to use certain features of the Services including but not limited to their identification documents (“KYC Documents”) The User hereby authorizes NoQu and any third-party service provider it may engage with or interact with in connection with using the Site to process KYC Documents and ascertain the User’s eligibility. The User agrees and warrants to provide valid, true, complete, and up-to-date KYC Documents. The User further acknowledges that any incorrect or misleading information provided shall constitute a material breach of these Terms, and the User’s access to certain features of the Services may be limited or denied in such event.</p>
        <h5>d. Incorrect/ Misleading Information</h5>
        <p>You must ensure that the information/ documents provided by you on registration is correct, complete and not misleading. In case of any change in the information provided by You, You must promptly inform Us of such changes by updating Your details, so that We may communicate with You effectively.</p>
        <h5>3. REFUND POLICY</h5>
        <h5>Refund of Subscription fee:</h5>
        <p>All fees and charges once paid are non-refundable.</p>
        <h5>4. DESCRIPTION OF SERVICES OFFERED</h5>
        <p>We provide a solution for employee(s) attendance management for businesses. By using Our Site, users can avail staff attendance and attendance reports.</p>
        <h5>5. RESPONSIBILITIES</h5>
        <h5>a. Our Responsibilities towards the Users</h5>
        <p>We will exercise reasonable skill and care with respect to the access of the Site by the Users. Although We have asked all users to use the Site responsibly, We cannot guarantee the accuracy, integrity or quality of any information You acknowledge and agree that We do not check or verify the details of any service bookings and do not guarantee the accuracy, integrity or quality of any information which is posted by third parties. It is hereby clarified that NoQu shall incur no liability in cases of non-compliance of applicable state and central labour laws with respect to payroll processing and other services availed on the Site.</p>
        <h5>b. Responsibilities of Users:</h5>
        <p>You agree to abide by the Terms of Use when using the Site. You shall be solely responsible for checking and verifying the details of any services accepted/ rendered on the Site by You and the terms of any support thereof. You shall be responsible for complying with all applicable laws including labour laws, local state and municipality laws and taxation regulations in your dealings with other Users and for the performance and quality of any support which You agree to provide to/ receive from a User.</p>
        <p>(i) You agree not to impersonate any person or entity, falsely claim, or otherwise misrepresent your affiliation with any person or entity, or access the accounts of others without permission, misrepresent the source, identity, perform any similar fraudulent activity or otherwise avail Services with what that we reasonably believe to be potentially fraudulent funds.</p>
        <p>(ii) By registering as a User and by using the Site, You agree to indemnify and hold us harmless from all costs, losses or claims which may result from any information you submit or transmit via the Site or from any support which You agree to provide to/ receive from any User.</p>
        <h5>6. IMPERSONATION AND UNAUTHORISED DEALINGS PROHIBITED</h5>
        <p>The Site does not tolerate any illegal and unauthorized activities on or against the Site by either Users or any unrelated third parties. All Users are absolutely prohibited from impersonating another person/User or deal in any other manner that is prohibited by the Laws of India and other Jurisdictions. If we have reasonable grounds to believe that a User has indulged in any prohibited activities or has committed any Crime or Cyber Crime, NoQu may in its sole discretion, but without any legal obligation to do so, initiate appropriate legal proceedings against the offender as well as notify the same to any regulatory or law enforcement agency of India or Foreign Jurisdiction. <b>NoQu may also suspend or terminate the User’s account and other privileges for the use of the Site.</b></p>
        <h5>7. CRIME AND CYBER CRIME REPORTING BY USERS</h5>
        <p>In case of any Cyber Crime and Cyber Contravention involving their accounts, Users alone are responsible to investigate, prosecute and file necessary legal actions and proceedings against the Cyber Criminals and other Offenders and NoQu shall in no case be responsible to share the financial and investigation burdens of the User. We will, however, endeavour to support Users in investigating such instances of Cyber Crime, if any, to the best of its ability.</p>
        <h5>8. USERNAME</h5>
        <p>After successful registration on the Site, a username (“ID”) will be generated for the use of the Site by You, which You must keep confidential. You shall be solely responsible for preventing any unauthorised use of Your ID and notify us in case any theft or unauthorized use of the ID takes place. We reserve the right to suspend and/ or block Your ID if the same is used in contravention of these Terms of Use. We are not responsible for changing / migrating the data from one User account to other.</p>
        <h5>9. USE OF SITE</h5>
        <p>The Site allows the registered users to create, edit and submit necessary information including creating User profile, posting details pertaining to the employee(s). We do not seek to monitor or control the submission of information. However, we do reserve the right to delete, move and edit any material submitted where We consider it necessary to do so. You agree to comply with all applicable laws and regulations when using the Site and are solely responsible for all the information You submit for inclusion or transmission. You must not post or transmit any material that(i) is fraudulent, dishonest or misleading; (ii) is unlawful, harassing, libellous, abusive, threatening, harmful, vulgar, obscene, or otherwise objectionable or breaches any law; (iii) encourages conduct that constitutes a criminal offence, gives rise to civil liability or otherwise breaches any applicable laws, regulations or code of practice; (iv) infringes the copyright or other rights of any third party; (v) is technically harmful (including, without limitation, computer viruses or other malicious software or harmful data). You grant Us a royalty-free, non-exclusive license to use, reproduce, modify, translate, make available and distribute the material for the purpose of operating the Site.</p>
        <h5>10. ALERTS/NOTIFICATIONS</h5>
        <p>We may from time to time provide automatic alerts/notifications and payment related alerts linked with Your Account on Site. Further, automatic alerts may be sent to you following certain changes to Your Account or information, such as changes in your registration information. By accepting the terms and conditions and/or using the Services, you accept that we may send the Email, SMS alerts to your registered mobile phone number, WhatsApp and through push notifications.</p>
        <p>(a) Electronic alerts will be sent to the mobile number provided by you via SMS, push notifications or WhatsApp for the Services. If your mobile number changes, you are responsible for informing us of that change. You can also choose to have alerts sent to a mobile device that accepts text messages. Changes to mobile number will apply to all of your alerts.</p>
        <p>(b) We will make best efforts to provide the Service and it shall be deemed that you shall have received the information sent from us as an alert on your registered mobile phone number and we shall not be under any obligation to confirm the authenticity of the person(s) receiving the alert. You cannot hold us liable for non-availability of the service in any manner whatsoever.</p>
        <p>(c) You further acknowledge that you shall have the obligation to inform us about any change in your mobile phone number or e-mail address. Alerts /notification will be sent to your new mobile number or e-mail address after registering and linking it with your Account. You acknowledge that the WhatsApp service or push notification or SMS provided by us is an additional facility provided for your convenience and that it may be susceptible to error, omission and/ or inaccuracy. In the event you observe any error in the information provided in the alert, you shall immediately inform us about the same. We will make best possible efforts to rectify the error as soon as possible.</p>
        <h5>11. GENERAL TERMS AND CONDITIONS</h5>
        <p>(a) You represent and warrant that you are an individual of legal age to form a binding contract (or if not, you’ve received your parent’s or guardian’s permission to use the Services and gotten your parent or guardian to agree to these Terms on your behalf).</p>
        <p>(b) To keep the Site up to date, you agree that we may automatically provide you with such updates without your further consent or notice to you. Please note that if the updates are not installed or such installation is stopped by You, Our Site may not operate properly or may not operate at all. We do not guarantee that we will make any updates available for Our Site, or that such updates will continue to support your device or system.</p>
        <p>(c) You may access and use the Site only for your personal/business and lawful purposes in accordance with these Terms of Use. You agree not to access the Site by any means other than through the interface that is provided by us.</p>
        <p>(d) You shall comply with any codes of conduct, policies or other notices that we provide to You or publish in connection with the use of the Site from time to time, and You shall promptly notify Us if You learn of a security breach related to the use of the Site. Additionally, you shall be responsible for complying with any laws, rules and regulations for the use of Our Site in Your jurisdiction.</p>
        <h5>12. MODIFICATIONS TO THE SITE</h5>
        <p>(a) We reserve the right to add, change, modify, discontinue or remove features from Our Site, at any time without cause, temporarily or permanently with or without any notice to you. You agree that we shall not be liable to You or to any third party for any modification, suspension or discontinuance of Our Site.</p>
        <p>(b) You shall not modify, adapt or hack the Site, or otherwise attempt to, gain unauthorized access to the Site or their related systems or networks.</p>
        <h5>13. TERMINATION OF SERVICES</h5>
        <p>We may suspend or cancel your registration and/ or terminate your access to the Site if you are in breach of these Terms of Use or have made any improper use of the Site. The suspension, cancellation or termination of your registration and your right to use the Site shall not affect either party’s statutory right or liabilities.</p>
        <h5>14. INTELLECTUAL PROPERTY RIGHTS</h5>
        <p>(a) Unless otherwise stated, the intellectual property rights in the Site (including without limitation all content, materials and technology used or appearing or transmitted through it) belongs to Us or Our licensors.</p>
        <p>(b) Subject to the terms and conditions of these Terms of Use, We hereby grant You a personal, non- transferable, non-sub licensable and non-exclusive right and license to use the Site solely in accordance with these Terms of Use, provided that You shall not (and shall not allow any third party to) copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code, or sell, assign, sublicense or otherwise transfer any right in the Site.</p>
        <h5>15. CONFIDENTIALITY</h5>
        <p>(a) You shall treat this Agreement as confidential. You shall not, except with Our prior written approval, disclose or make any public or other announcements of any aspect covered by these Terms of Use and any other relevant information and documents, the contents of which are made available to You with respect to the use by you of the Site, unless required to do so and to the extent necessary under these Terms of Use, on a need to know basis, while always ensuring that the persons to whom such information and documents are disclosed maintain the strictest confidentiality of the same.</p>
        <p>(b) We reserve the right to disclose any information/ documents pertaining to the User and/ or any transaction on the Site, in the event such information/ documents:</p>
        <p>(i) Have ceased to be confidential without default on our part;</p>
        <p>(ii) Have been received from a third party who did not receive it in confidence; and</p>
        <p>(iii) We are required by any court, government or other regulatory body to disclose, but only to the extent required by law.</p>
        <h5>16. PRIVACY</h5>
        <p>Our Privacy Policy explains how we collect, process, use and disclose registration information and other Personal Information about you. For the definition of Personal Information and full details, please see our Privacy Policy at www.noqu.in/privacy-policy</p>
        <h5>17. DISCLAIMERS</h5>
        <p>(a) We endeavour to ensure that the information available on or through the use of the Site is correct, up to date and accurate. We are mere service providers, you use the services at Your own risk. However, we do not warrant the accuracy and completeness of such information. Any content downloaded or otherwise obtained through the use of the Services is downloaded at your own risk, and you will be solely responsible for any damage to your property or loss of data that results from such download. No advice or information, whether oral or written, obtained by you from us or through the Services will create any warranty not expressly stated herein.</p>
        <p>(b) We will not be liable to you for any loss or damage whatsoever or howsoever caused or arising, directly or indirectly, including without limitation, as a result of loss of data; interruption or stoppage of access to payment gateway; interruption or stoppage of the Site; non-availability of connectivity links/hyperlinks. Our sole obligation and your sole and exclusive remedy in the event of interruption in Services or loss of use and/or access to Services, will be to use all reasonable endeavours to restore the Services and/or access as soon as reasonably possible.</p>
        <p>(c) The Site permits you to access and receive information supplied by third parties. The third parties submitting this information are responsible for ensuring that it is accurate and complies with all the relevant laws. We will not be responsible to you for the conduct of any such third party or for any error or inaccuracy in the information submitted by them. We make no promise that the Site will meet your requirements or that the Site will be free of fault or continuously available. Your access to the Site may occasionally be restricted to allow for repairs, maintenance or the introduction of new features.</p>
        <h5>18. INDEMNITY</h5>
        <p>(a) You shall defend, indemnify, and hold harmless Us, Our affiliate companies, directors, associates, agents and officers from and against any loss, expenses, claims, actions or demands, including without limitation reasonable legal and accounting fees, arising or resulting from Your breach of these Terms of Use or violation of any third party rights by You hereunder.</p>
        <p>(b) We shall not provide notice to you of any such claim, suit or demand. Further, We reserve the right to assume the exclusive defense and control of any matter which is subject to indemnification under this clause. In such case, you agree to cooperate with any reasonable requests assisting Our defense of such matter.</p>
        <p>(c) The obligations contained in this clause shall survive the termination of the Terms of Use with You and Your use of Our Services.</p>
        <h5>19. LIMITATION OF LIABILITY</h5>
        <p>In no event, NoQu or its contractors, agents, licensors, partners or suppliers will be liable to You for direct, indirect, ancillary, special, incidental, consequential, punitive, reliance or exemplary damages. This includes, but is not limited to injury, claim, loss of data, loss of income, loss of profit or loss of opportunity, loss of or damage to property, loss of anticipated profits or any other pecuniary or non-pecuniary loss , goodwill, use, data, other intangible, or damage of any nature whatsoever loss (even if NoQu has been advised of the possibility of such damages), arising out of or relating to:</p>
        <p>(i) this Agreement or any other policies of the Website;</p>
        <p>(ii) the Services, the Website or any reference site/app/service; or</p>
        <p>(iii) Your use or inability to use the Services, the Website (including any and all materials) or any reference sites/app/service, even if we or our authorized representative has been advised of the possibility of such damages; or</p>
        <p>(iv) any other interactions with NoQu.</p>
        <h5>20. FORCE MAJEURE</h5>
        <p>In the event that the performance of any of Our obligations pursuant to these Terms of Use is prevented, hindered or delayed by reason of fire, flood, earthquake, explosion or other casualty or accident or act of God, war or other violence, or service interruptions caused by the hosting service, failure or any act by or nature of telecommunications carrier, of the internet backbone, of any internet servers, or any applicable law, order proclamation, interruptions in supply of electricity regulation, ordinance, demand or requirement of any governmental or regulatory authority and such non-performance, hindrance or delay could not have been prevented by reasonable foresight or precautions (including proper planning and execution of the disaster recovery or business continuity plan) or circumvented through the use of alternate sources, work-around plans or other means or any applicable law, order proclamation, regulation, ordinance, demand or requirement of any governmental or regulatory authority ( collectively “Force Majeure Event”), then We will be excused for such non-performance, hindrance or delay, as applicable, from Our obligations hereunder, to the extent that they are affected by the Force Majeure Event.</p>
        <h5>21. Complaint procedure</h5>
        <p>You can reach us at support@noqu.in or contact us at 24x7 Hours Customer Support at +91 7401600600 in case of any query and/or complaints.</p>
        <h5>22. NOTICES</h5>
        <p>All notices shall be sent to Us/ You via email or at the postal address provided herein below: Door No - 84, 2nd floor, Murugesan Naicker Complex, Greams Rd, Thousand Lights West, Thousand Lights, Chennai, Tamil Nadu 600006, India.</p>
        <h5>23. GOVERNING LAW</h5>
        <p>These Terms of Use shall be governed by and construed in accordance with the laws of India. The parties subject themselves to the exclusive jurisdiction of the courts at Chennai, India.</p>
        <h5>24. DISPUTE RESOLUTION</h5>
        <p>Any dispute in respect of all or any of the provisions of these Terms of Use shall be resolved amicably within 15 (fifteen) days of notifying the same to the other party and in the event neither party reaches an agreement, the dispute should be resolved by Arbitration which shall be referred to a Sole Arbitrator in accordance with the provisions of the Arbitration and Conciliation Act 1996. The place of arbitration shall be Chennai, India and the language used shall be English.</p>
        <h5>25. ENTIRE AGREEMENT</h5>
        <p>The Terms of Use and the Privacy Policy represent the entire agreement between You and Us in relation to the use of Our Site and shall supersede any prior agreement, understanding or arrangement between Us, whether oral or in writing. Further, you acknowledge and agree that, you have not relied on any representation, undertaking, promise or implied any warranty, whether conveyed orally or in writing, except as expressly stated herein.</p>
        <h5>26. CHANGE IN TERMS OF USE</h5>
        <p>We reserve the right to change these Terms of Use at any time. You are expected to check and get acquainted with these Terms of Use from time to time.</p>
        <h5>27. WAIVER</h5>
        <p>No delay in enforcing any provision of the Terms of Use will be construed to be a waiver of any rights under that provision by us.</p>
        <h5>28. ASSIGNMENT</h5>
        <p>You shall not assign any of your rights or obligations under these Terms of Use without Our prior written consent.</p>
        <h5>29. SEVERABILITY</h5>
        <p>If any provision of these Terms of Use is held by a court of competent jurisdiction to be void, invalid, unenforceable or illegal, the remaining provisions shall remain in full force and effect. I hereby agree to these Terms of Use.</p>
        <p>These Terms of Use has been last updated on 11/03/2024</p>

    </div>
  )
}

export default TermsAndConditions
